### ISSUE TITLE
electron-drag breaks when using 'affinity'

### ISSUE THREAD

**Issue by ChazDazzle** [kapetan/electron-drag#10]
There's a new option in Electron 2.0 called 'affinity' which allows multiple windows to be run in the same render process. Using electron-drag with affinity works for the first window in the group, but the win-mouse tryRequire throws an error on all subsequent windows:

```
C:\Users\Chaz\Documents\pokeit-hud-x64\node_modules\bindings\bindings.js:88 Uncaught Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\Chaz\Documents\pokeit-hud-x64\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\Chaz\Documents\pokeit-hud-x64\node_modules\win-mouse\index.js:3:13)
```

**Comment by ChazDazzle** [comment]
See: https://github.com/nodejs/node/pull/19731#issuecomment-379516708

**Comment by ChazDazzle** [comment]
Using the well known symbol approach to define the add-on appears to work: https://github.com/nodejs/node/commit/3828fc6289783a632b00270d6b72b5c5bdd6437d

**Comment by wuwei2150** [comment]
@ChazDazzle Has the problem been solved?

**Comment by kapetan** [comment]
I'm not planning on fixing this, affinity seems to be going away. Version 2.0.0 is now context-aware at least.
