### ISSUE TITLE
An ERROR after require('electron-drag')

### ISSUE THREAD

**Issue by RoryJYL** [kapetan/electron-drag#16]
When I had troubles in dragging window, I saw this project and I install it.
But when I require with `require('electron-drag')` in the .vue, the console drop these error:
```
Uncaught Error: Could not locate the bindings file. Tried:
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\build\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\build\Debug\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\build\Release\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\out\Debug\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\Debug\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\out\Release\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\Release\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\build\default\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\compiled\8.9.3\win32\x64\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\addon-build\release\install-root\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\addon-build\debug\install-root\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\addon-build\default\install-root\addon.node
 → A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\lib\binding\node-v57-win32-x64\addon.node
    at bindings (A:\desktop\project\orderer\orderer\node_modules\_bindings@1.5.0@bindings\bindings.js:126)
    at Object.<anonymous> (A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\index.js:3)
    at Object.<anonymous> (A:\desktop\project\orderer\orderer\node_modules\_win-mouse@1.3.0@win-mouse\index.js:41)
    at Module._compile (module.js:642)
    at Object.Module._extensions..js (module.js:653)
    at Module.load (module.js:561)
    at tryModuleLoad (module.js:504)
    at Function.Module._load (module.js:496)
    at Module.require (module.js:586)
    at require (internal/module.js:11)
```
And I tried to rebuild with `npm rebuild` and it dropped these error:
```
> osx-mouse@1.3.1 install A:\desktop\project\orderer\orderer\node_modules\_osx-mouse@1.3.1@osx-mouse
> node-gyp rebuild


A:\desktop\project\orderer\orderer\node_modules\_osx-mouse@1.3.1@osx-mouse>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\HP\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd A:\desktop\project\orderer\orderer\node_modules\_osx-mouse@1.3.1@osx-mouse
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! osx-mouse@1.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osx-mouse@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2020-01-21T08_43_00_771Z-debug.log
```
I don't know how to fix it.
My platform is Windows 10, I saw an issue with osx-mouse, and its solution is to add `"os":  "darwin],` in pakage.json for osx-mouse, but that already existed in that pakage.json.
Someone could help me?

**Comment by kapetan** [comment]
You have to build with the correct Electron headers as mentioned in the readme.
