### ISSUE TITLE
NODE_MODULE_VERSION Error

### ISSUE THREAD

**Issue by weedsboy** [kapetan/electron-drag#22]
Uncaught Error: The module '\\?\C:\Code\pc\node_modules\win-mouse\build\Release\addon.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (C:\Code\pc\node_modules\win-mouse\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Code\pc\node_modules\win-mouse\index.js:3:13)

--------------------------------------------------------------------------------------

But id dosn't find the version "80" in https://nodejs.org/en/download/releases/
What should I do with this error?

**Comment by kapetan** [comment]
Have you built the module with the correct electron headers as it says in the readme: https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by weedsboy** [comment]
Thanks @kapetan
